spring:
  application:
    name: blog-app

  jpa:
    hibernate:
      ddl-auto: update

  # file config
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  profiles:
    active: dev

project:
  image: images/