spring:

  # db config
  datasource:
    url: jdbc:h2:file:C:/Users/nikunjd1/test
    driverClassName: org.h2.Driver
    userName: sa
    password: Password
    platform: h2

  jpa:
    show-sql: true

  h2:
    console:
      enabled: true
      path: /h2-console